server:
  port: 8080

spring:
  mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER 
  data:
    mongodb:
      uri: ${MONGO_URI}

jwt:
  secret: ${JWT_SECRET}
  expirationMs: 86400000  # 1 day

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method

